canonical: https://gematik.de/fhir/vsdm2
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
#id: Specification VSDM 2
#name: Specification VSDM 2
#status: active
#version: "1.0.0"
#publisher:
#  name: Gematik GmbH
#  url: https://www.gematik.de/
#  email: info@gematik.de
dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.5.4
  de.gematik.terminology: 1.0.8
  de.gematik.ti: 1.2.0
  kbv.basis: 1.8.0
  kbv.all.st: 1.34.0
  kbv.ita.for: 1.3.0
